version: '3'

services:
  kafka-1:
    image: bitnami/kafka:latest
    container_name: kafka-payment
    ports:
      - "9092:9092"
    user: root
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_KRAFT_CLUSTER_ID: e23dc448-3234-49ff-a345-021e62e40a3e
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-payment:9091
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092 #Внутрение порты можно вообще ничего не менять
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-payment:9090,EXTERNAL://${HOSTNAME:-localhost}:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - kafka-payment_volume:/bitnami/kafka


  postgres:
    container_name: postgres-payment
    image: postgres:16-alpine
    volumes:
      - postgres-payment_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: payment_db
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "docker_app" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres-payment_volume:
  kafka-payment_volume: